title: Hyoungseok's memoir
description: a gopher collecting whatever it comes across
theme: just-the-docs

url: https://balmdui.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
